# Generated by Django 5.0.6 on 2024-06-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.JSONField(default=list),
        ),
    ]
